language: go
go:
  - "1.10.x"
  - master

before_install:
- pwd

install: true

script:
  - env GO111MODULE=on go vet -v -all -shadow ./...
  - env GO111MODULE=on go test -timeout 1m -v -race -cover -coverprofile=coverage.txt ./... && bash <(curl -s https://codecov.io/bash)
  - env GO111MODULE=on go test -timeout 1m -v -race -run=XXXX -bench=. ./...
  - env GO111MODULE=on go build 
  - env GO111MODULE=on go test
